-- Ordem de cadastro: casas, prédios e apartamentos passam a ser listados na
-- ordem em que foram cadastrados (a ordem do percurso na quadra), e não em
-- ordem alfanumérica. A coluna seq é crescente e única.

ALTER TABLE addresses ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE units ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY;

-- Preenche os registros existentes respeitando a ordem de cadastro.
WITH o AS (SELECT id, row_number() OVER (ORDER BY created_at, id) AS rn FROM addresses)
UPDATE addresses a SET seq = o.rn FROM o WHERE o.id = a.id;

-- Apartamentos cadastrados no mesmo lote têm o mesmo horário; para eles mantém-se
-- a ordem natural (bloco/torre e número), que é a ordem em que o lote foi montado.
WITH o AS (
  SELECT id, row_number() OVER (
    ORDER BY created_at, tower,
             NULLIF(regexp_replace(identifier, '\D', '', 'g'), '')::bigint NULLS LAST,
             identifier, id) AS rn
  FROM units
)
UPDATE units u SET seq = o.rn FROM o WHERE o.id = u.id;

-- Próximos valores continuam a partir do maior já usado.
SELECT setval(pg_get_serial_sequence('addresses', 'seq'), COALESCE((SELECT max(seq) FROM addresses), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('units', 'seq'), COALESCE((SELECT max(seq) FROM units), 0) + 1, false);

ALTER TABLE addresses ALTER COLUMN seq SET NOT NULL;
ALTER TABLE units ALTER COLUMN seq SET NOT NULL;
CREATE INDEX addresses_block_seq_idx ON addresses(block_id, seq);
CREATE INDEX units_address_seq_idx ON units(address_id, seq);
